name = "wisp-signaling"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[durable_objects.bindings]]
name = "WISP_ROOM"
class_name = "WispRoom"

[[durable_objects.bindings]]
name = "WISP_PRESENCE"
class_name = "WispPresence"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["WispRoom"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["WispPresence"]
